flask_app/webapp/routes.py
from flask import render_template, request, Blueprint
from datetime import datetime

bp = Blueprint('webapp', __name__, template_folder='templates',)


@bp.route('/')
def index():
    return render_template('index.jinja2')

@bp.route('/map')
def map():
    return render_template('map.jinja2')

@bp.route('/chart')
def chart():
    return render_template('chart.jinja2')

flask_app/webapp/templates/base.jinja2
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  {% block customCSS %}{% endblock %}
  {% block customSources %}{% endblock %}
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="/">Chiri</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('webapp.map')}}">Map View</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('webapp.chart')}}">Charts</a>
              </li>
              {# <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li> #}
            </ul>
          </div>
        </nav>
      </div>
    </div>
    <div class="row">
      <div class="col">
        {% block body %}{% endblock %}
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  {% block customJS %}{% endblock %}
</body>

</html>

flask_app/webapp/templates/chart.jinja2
{% extends "base.jinja2" %}
{% block customSources %}<script src="https://cdn.plot.ly/plotly-2.27.0.min.js" charset="utf-8"></script>{% endblock %}
{% block body%}
<div id="tester" style="width:600px;height:250px;"></div>
<div id="barChart" style="width:600px;height:250px;"></div>
<button id="showData">Show data</button>
{% endblock %}
{% block customJS %}
<script src="{{ url_for('static', filename='chart.js') }}"></script>
{% endblock %}

flask_app/webapp/templates/index.jinja2
{% extends "base.jinja2" %}
{% block body %}{% endblock %}

flask_app/webapp/templates/map.jinja2
{% extends "base.jinja2" %}

{% block title %} MAP {% endblock %}
{% block customSources %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
    integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
    crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
    crossorigin=""></script>
<link rel="stylesheet" href="{{ url_for('static', filename='MarkerCluster.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='MarkerCluster.Default.css') }}">
{% endblock %}

{% block body %}
<div class="container-fluid" style="height: 100%; width: auto;">
    <div class="row">
        <div class="col-md-2 text-center">
            <div class="row">
                <div class="col-md-12" style="height: 80vh; overflow-y:scroll;">
                    <!-- Dropdown para días de la semana -->
                    <label class="form-label" for="dia_semana">Día de la Semana:</label>
                    <select class="form-select" id="dia_semana">
                    <option value="">-</option>
                    <option value="Domingo">Domingo</option>
                    <option value="Lunes">Lunes</option>
                    <option value="Martes">Martes</option>
                    <option value="Miércoles">Miércoles</option>
                    <option value="Jueves">Jueves</option>
                    <option value="Viernes">Viernes</option>
                    <option value="Sábado">Sábado</option>
                    </select>
                    <br>

                    <!-- Dropdown para tipo de incidente -->
                    <label class="form-label" for="tipo_incidente_c4">Tipo de Incidente:</label>
                    <select class="form-select" id="tipo_incidente_c4">
                    <option value="">-</option>
                    <option value="Accidente">Accidente</option>
                    <option value="Cadáver">Cadáver</option>
                    <option value="Detención ciudadana">Detención ciudadana</option>
                    <option value="Lesionado">Lesionado</option>
                    <option value="Mi Calle">Mi Calle</option>
                    <option value="Mi Taxi">Mi Taxi</option>
                    <option value="Sismo">Sismo</option>
                    </select>
                    <br>

                    <!-- Dropdown para tipo de accidente de tránsito -->
                    <label class="form-label" for="incidente_c4">Tipo de Accidente de Tránsito:</label>
                    <select class="form-select" id="incidente_c4">
                    <option value="">-</option>
                    <option value="Accidente automovilístico">Accidente automovilístico</option>
                    <option value="Atropellado">Atropellado</option>
                    <option value="Choque con lesionados">Choque con lesionados</option>
                    <option value="Choque con prensados">Choque con prensados</option>
                    <option value="Choque sin lesionados">Choque sin lesionados</option>
                    <option value="Ciclista">Ciclista</option>
                    <option value="Ferroviario">Ferroviario</option>
                    <option value="Incidente de tránsito">Incidente de tránsito</option>
                    <option value="Monopatín">Monopatín</option>
                    <option value="Motociclista">Motociclista</option>
                    <option value="Otros">Otros</option>
                    <option value="Persona atrapada / desbarrancada">Persona atrapada / desbarrancada</option>
                    <option value="Persona atropellada">Persona atropellada</option>
                    <option value="Vehiculo atrapado">Vehiculo atrapado</option>
                    <option value="Vehiculo desbarrancado">Vehiculo desbarrancado</option>
                    <option value="Vehiculo atrapado varado">Vehículo atrapado/varado</option>
                    <option value="Volcadura">Volcadura</option>
                    </select>
                    <br>

                    <!-- Dropdown para alcaldías -->
                    <label class="form-label" for="alcaldia_inicio">Alcaldía:</label>
                    <select class="form-select" id="alcaldia_inicio">
                    <option value="">-</option>
                    <option value="ALVARO OBREGON">ALVARO OBREGON</option>
                    <option value="AZCAPOTZALCO">AZCAPOTZALCO</option>
                    <option value="BENITO JUAREZ">BENITO JUAREZ</option>
                    <option value="COYOACAN">COYOACAN</option>
                    <option value="CUAJIMALPA DE MORELOS">CUAJIMALPA DE MORELOS</option>
                    <option value="CUAUHTEMOC">CUAUHTEMOC</option>
                    <option value="GUSTAVO A. MADERO">GUSTAVO A. MADERO</option>
                    <option value="IZTACALCO">IZTACALCO</option>
                    <option value="IZTAPALAPA">IZTAPALAPA</option>
                    <option value="LA MAGDALENA CONTRERAS">LA MAGDALENA CONTRERAS</option>
                    <option value="MIGUEL HIDALGO">MIGUEL HIDALGO</option>
                    <option value="MILPA ALTA">MILPA ALTA</option>
                    <option value="NA">NA</option>
                    <option value="TLAHUAC">TLAHUAC</option>
                    <option value="TLALPAN">TLALPAN</option>
                    <option value="VENUSTIANO CARRANZA">VENUSTIANO CARRANZA</option>
                    <option value="XOCHIMILCO">XOCHIMILCO</option>
                    </select>
                    <br>

                    <!-- Dropdown para letras -->
                    {# <label for="letras">Letra:</label>
                    <select id="letras">
                    <option value="">-</option>
                    <option value="A">A</option>
                    <option value="D">D</option>
                    <option value="F">F</option>
                    <option value="I">I</option>
                    <option value="N">N</option>
                    </select>
                    <br> #}

                    <!-- Dropdown para categoría de incidente -->
                    <label class="form-label" for="clas_con_f_alarma">Categoría de Incidente:</label>
                    <select class="form-select" id="clas_con_f_alarma">
                    <option value="">-</option>
                    <option value="DELITO">DELITO</option>
                    <option value="EMERGENCIA">EMERGENCIA</option>
                    <option value="FALSA ALARMA">FALSA ALARMA</option>
                    <option value="INCIDENTES EXTERNOS">INCIDENTES EXTERNOS</option>
                    <option value="URGENCIAS MEDICAS">URGENCIAS MEDICAS</option>
                    </select>
                    <br>

                    <!-- Dropdown para herramientas -->
                    <label class="form-label" for="tipo_entrada">Herramienta:</label>
                    <select class="form-select" id="tipo_entrada">
                    <option value="">-</option>
                    <option value="APLICATIVOS">APLICATIVOS</option>
                    <option value="BOTÓN DE AUXILIO">BOTÓN DE AUXILIO</option>
                    <option value="CÁMARA">CÁMARA</option>
                    <option value="LECTOR DE PLACAS">LECTOR DE PLACAS</option>
                    <option value="LLAMADA APP911">LLAMADA APP911</option>
                    <option value="LLAMADA DEL 066">LLAMADA DEL 066</option>
                    <option value="LLAMADA DEL 911">LLAMADA DEL 911</option>
                    <option value="NA">NA</option>
                    <option value="RADIO">RADIO</option>
                    <option value="REDES">REDES</option>
                    <option value="SOS MUJERES *765">SOS MUJERES *765</option>
                    <option value="ZELLO">ZELLO</option>
                    </select>
                    <br>
                    <label class="form-label" for="inicio">Inicio:</label>
                    <input class="form-control" id="inicio" type="date" min="2013-01-01" max="2023-12-31" value="2013-01-01">
                    <br>
                    <label class="form-label" for="final">Final:</label>
                    <input class="form-control" id="final" type="date" min="2013-01-01" max="2023-12-31" value="2023-12-31">
                    <br>

                    <label class="form-label" for="limit">Limit:</label>
                    <input class="form-control" id="limit" type="number" min="1" max="5000" value="100">
                </div>
            </div>
            <div class="row" style="padding-top: 20px;">
                <div class="col-md-12 justify-content-center" style="height: 40px;">
                    <button class="btn btn-success" id="apply" style="width: 100%; height: 95%;">Apply</button>
                </div>
            </div>
            
        </div>
        {# <div class="col-md-8"> #}
        <div id="map" class="col-md-10"></div>
        {# </div> #}
    </div>
</div>
{% endblock %}

{%block customJS%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.3/leaflet.markercluster.js" integrity="sha512-OFs3W4DIZ5ZkrDhBFtsCP6JXtMEDGmhl0QPlmWYBJay40TT1n3gt2Xuw8Pf/iezgW9CdabjkNChRqozl/YADmg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/heatmap.js/2.0.0/heatmap.min.js" integrity="sha512-FpvmtV53P/z7yzv1TAIVH7PNz94EKXs5aV6ts/Zi+B/VeGU5Xwo6KIbwpTgKc0d4urD/BtkK50IC9785y68/AA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{{ url_for('static', filename='leaflet-heatmap.js') }}"></script>
<script src="{{ url_for('static', filename='map.js') }}"></script>
{%endblock%}